### ISSUE TITLE
Switch to new vimeo broke module

### ISSUE THREAD

**Issue by surfjedi** [r0nn1ef/Silverstripe-Vimeo-Service-module#1]
On a site I'm developing, the client switch the vimeo account to the new vimeo.

Now the module has stopped working, and just says the user or group/album has no videos.

ANy ideas on how to fix?

Thanks in advance

**Comment by r0nn1ef** [comment]
Can you provide me with a little more information?

First, what do you mean "...the client switch the vimeo account to the new
vimeo"? Did they create a new vimeo account? If that is the case, that is
why it says the user or group/album has no videos. They will need to
transfer or re-upload the videos from the old account to the new account or
in the textfield for "Vimeo Username/Vimeo Group Name/Vimeo Album ID" you
will need to enter the old account information.

If you need more help, please email me directly at
r0nn1ef8580@gmail.comwith the old and new account ID's and we will
take this offline to get you
going.

--ron

On Thu, Mar 29, 2012 at 11:49 PM, surfjedi <
reply@reply.github.com

> wrote:
> 
> On a site I'm developing, the client switch the vimeo account to the new
> vimeo.
> 
> Now the module has stopped working, and just says the user or group/album
> has no videos.
> 
> ANy ideas on how to fix?
> 
> Thanks in advance
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/r0nn1ef/Silverstripe-Vimeo-Service-module/issues/1

## 

---

Ronald Ferguson
www.ronaldferguson.net
r0nn1ef@ronaldferguson.net | r0nn1ef8580@gmail.com
cell [682] 234 - 1321

"Don't tell people how to do things, tell them what to do and let them
surprise you
with their results." -- Gen. George S. Patton, Jr. (USA)

**Comment by surfjedi** [comment]
Thanks, i will email you direct soon.  I love your module, its brilliant.

The issue is that vimeo has got a new "vimeo" version a user can optionaly use.  And after we switched to that the module stopped working and gettting the video feeds from vimeo.

But ill email you direct

**Comment by r0nn1ef** [comment]
I just created a new account on Vimeo and switched to the new Vimeo. I will try to see what is going on with the new setup, but no promises on a fix until Vimeo forces everyone to switch. Check this thread for updates.

**Comment by r0nn1ef** [comment]
@surfjedi 

I've been doing some research on this which included a base SilverStripe install with the code for my module downloaded from silverstripe.org. I could not reproduce the error that you were talking about. I then started digging in the Vimeo forums and it appears that my module is not the only api client that is experiencing this problem. 

I found one thread specifically where several TubePress users are getting the same error that you have been getting. (http://vimeo.com/forums/topic:49430) This leads me to believe that something isn't right over on Vimeo's side with the authentication of the api key and secret key. Close to the bottom of the thread, there is a lot of posts about a trailing space in the API Consumer Key value. Most are saying if that is removed that everything works fine.

I've updated the repository with some code that should hopefully solve the problem. I've added trim() to the consumer and secret key setters.

**Comment by surfjedi** [comment]
Hi Ron,
Thanks, I appriciate you letting me know.  I love your module, and 
hopefully i can get it going again.

Ill dig around some more and see if i can get more info for you.

Lee Blazek

  BERZERK\* interactive

```
Web, Mobile, and Mobile App Development
```

+64(0)21-55-63-55 | +64(0)3-443-4261

www.BERZERK.co.nz http://www.berzerk.co.nz

/*Attitude included no extra Charge/

```
Our Latest apps
```

Queenstown Happy Hour - for iPhone http://www.queenstownhappyhour.com

Wanaka Happy Hour - for iPhone http://www.wanakahappyhour.com

**Comment by r0nn1ef** [comment]
## LinkedIn

I'd like to add you to my professional network on LinkedIn.
- Ron

Ron Ferguson
Sr. Web Developer/Software Engineer at HousingWire
Dallas/Fort Worth Area

Confirm that you know Ron Ferguson:
https://www.linkedin.com/e/-8qx1p1-h3d56psf-1b/isd/7460893174/fjXV8r-R/?hs=false&tok=3NpJ1n0PMhG5g1

## 

You are receiving Invitation to Connect emails. Click to unsubscribe:
http://www.linkedin.com/e/-8qx1p1-h3d56psf-1b/ow4R6lWk14NXwLfcoIpBh-9uE-YoXpPgz91gLNem3kOowColm98cpNPFe85awCdWzRVBZo5IekSGu1Z1zdCbLROVekl2q1PMXwj3GOovP_EErvk8/goo/reply%2Bi-3892579-cdd4251a37779e1752f0c6e3f67b87f993a6bb86-879793%40reply%2Egithub%2Ecom/20061/I2531952058_1/?hs=false&tok=32n-yOMz0hG5g1

(c) 2012 LinkedIn Corporation. 2029 Stierlin Ct, Mountain View, CA 94043, USA.
