### ISSUE TITLE
What is the actual short code?

### ISSUE THREAD

**Issue by surfjedi** [r0nn1ef/Silverstripe-Vimeo-Service-module#2]
Sorry i have searched the docs, and read me for the actual short code to embed in txt fields.  But can't seem to sort it out?

For example after i install module, I have got gallery pages going fine.

But For short code embedding in any the general page what is the short code? is it $Vimeo.??

**Comment by anselmdk** [comment]
Hi,
the method `VimeoShortcutHandler` on `VimeoGalleryPage.php` should explain this.  
You can find it here: https://github.com/r0nn1ef/Silverstripe-Vimeo-Service-module/blob/master/code/VimeoGalleryPage.php#L116

**Comment by r0nn1ef** [comment]
I've added some better documentation to my website. you should be able to
get all of the information that you need from there.

http://www.ronferguson.net/documentation/vimeo-service-module-documentation/installation-and-configuration

--ron

On Fri, Oct 5, 2012 at 8:13 AM, Anselm Christophersen <
notifications@github.com> wrote:

> Hi,
> the method VimeoShortcutHandler on VimeoGalleryPage.php should explain
> this.
> 
> You can find it here:
> https://github.com/r0nn1ef/Silverstripe-Vimeo-Service-module/blob/master/code/VimeoGalleryPage.php#L116
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/r0nn1ef/Silverstripe-Vimeo-Service-module/issues/2#issuecomment-9174847.

## 

---

Ronald Ferguson
r0nn1ef8580@gmail.com
cell [682] 234 - 1321

"Don't tell people how to do things, tell them what to do and let them
surprise you
with their results." -- Gen. George S. Patton, Jr. (USA)

The information contained in this e-mail may be confidential and/or
privileged. This e-mail is intended to be reviewed by only the individual
or entity named above. If you are not the intended recipient or an
authorized representative of the intended recipient, you are hereby
notified that any review, dissemination or copying of this e-mail and its
attachments, if any, or the information contained herein is prohibited. If
you have received this e-mail in error, please immediately notify the
sender by return e-mail and delete this e-mail from your system.
